#!/bin/bash

python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py
python train_batch_multiRank_inductive_reddit_Mixlayers_sampleA.py

